baseurl = "https://radare.today"
languageCode = "en-us"
title = "The Official Radare Blog"
Paginate = 10
theme = "ananke"

[params]
name = "The radare team"
description = "The blog of radare2"
bio = ""
twitter = "radareorg"
copyright = "The radare team"
enableRSS = true

about = "https://www.radare.org"
tweet = "https://twitter.com/radareorg"
